version: "3.9"

services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j
    restart: always
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_AUTH=${NEO4J_USER}/${NEO4J_PASSWORD}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
  
  # api:
  #   image: node:18.14.2
  #   container_name: api
  #   restart: always
  #   env_file:
  #    - .env
  #   ports:
  #     - ${APP_PORT}:${APP_PORT}
  #   volumes:
  #     - .:/usr/src/app
  #   working_dir: /usr/src/app
  #   command: npm run start
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: "10m"
  #       max-file: "5"